// tracks/health/track.config.js
// Worlds extracted verbatim from degree-sheets/kiosk-health/world-map.js
// tileTint/tileDesc extracted verbatim from degree-sheets/kiosk-health/generate.js
// copy strings extracted from degree-sheets/kiosk-health/public/app.js
export default {
  id: 'health',
  title: 'Central Piedmont — Explore Health Sciences Programs',
  fleet: 'cpcc-health-kiosk',
  pagesBase: 'https://centralpiedmont.github.io/degree-explorer/health/sheets',
  infoSessionUrl: 'https://www.cpcc.edu/events/health-programs-info-fair',
  theme: { /* track colors are supplied by world entries + styles.css vars; reserved for future overrides */ },
  features: { worldTilePhotos: true, admissions: true, specializations: true },
  copy: {
    topbarLabel: 'Health Sciences',
    attractSub: 'Explore 16 Health Sciences programs and find yours in three taps.',
    infoButton: 'Find a Health Sciences info session',
    ceHeading: 'Certifications &amp; Short Courses',
    resultEyebrow: 'YOUR HEALTH SCIENCES MATCH',
  },
  tileTint: {},
  tileDesc: {
    'nursing-adn': 'Advanced nursing leadership and practice',
    'practical-nursing': 'Deliver daily patient care and support',
    'nurse-aide': 'Assist patients with daily activities',
    'physical-therapist-assistant': 'Help patients restore movement and strength',
    'occupational-therapy-assistant': 'Support patients in daily living skills',
    'surgical-technology': 'Prepare surgical suites and assist surgeons',
    'respiratory-therapy': 'Manage breathing and ventilation systems',
    'cardiovascular-technology': 'Monitor and test heart and blood vessels',
    'polysomnography': 'Diagnose sleep disorders and conditions',
    'medical-laboratory-technology': 'Analyze samples and conduct medical tests',
    'pharmacy-technology': 'Prepare and dispense medications',
    'dental-hygiene': 'Clean teeth and educate on oral health',
    'dental-assisting': 'Support dentists in patient care',
    'ophthalmic-medical': 'Assist eye doctors and conduct vision tests',
    'emergency-medical-science': 'Respond to medical emergencies',
    'medical-assisting': 'Support doctors in clinics and offices',
  },
  worlds: [
    { id: 'nursing', name: 'Nursing & Bedside Care',
      desc: 'Care for patients at the bedside',
      color: '#005D83', text: '#FFFFFF',
      programIds: ['nursing-adn', 'practical-nursing', 'nurse-aide'] },
    { id: 'therapy', name: 'Therapy & Rehabilitation',
      desc: 'Help people move, recover, and regain independence',
      color: '#54565A', text: '#FFFFFF',
      programIds: ['physical-therapist-assistant', 'occupational-therapy-assistant'] },
    { id: 'surgery', name: 'Surgery & Critical Care',
      desc: 'Work in the OR, ICU, and acute-care teams',
      color: '#B4A269', text: '#1A1A1A',
      programIds: ['surgical-technology', 'respiratory-therapy', 'cardiovascular-technology', 'polysomnography'] },
    { id: 'labs', name: 'Labs, Meds & Diagnostics',
      desc: 'Run the tests and medications behind every diagnosis',
      color: '#54565A', text: '#FFFFFF',
      programIds: ['medical-laboratory-technology', 'pharmacy-technology'] },
    { id: 'dentalvision', name: 'Dental & Vision Care',
      desc: 'Care for smiles and sight',
      color: '#672666', text: '#FFFFFF',
      programIds: ['dental-hygiene', 'dental-assisting', 'ophthalmic-medical'] },
    { id: 'emergency', name: 'Emergency & Clinic Support',
      desc: 'Respond to emergencies and keep clinics running',
      color: '#005D83', text: '#FFFFFF',
      programIds: ['emergency-medical-science', 'medical-assisting'] },
  ],
};
