// tracks/tech/track.config.js
// Worlds extracted verbatim from degree-sheets/kiosk/world-map.js
// tileTint/tileDesc extracted verbatim from degree-sheets/kiosk/generate.js
// copy strings extracted from degree-sheets/kiosk/public/app.js
export default {
  id: 'tech',
  title: 'Central Piedmont — Explore IT Degrees',
  fleet: 'cpcc-degree-kiosk',
  pagesBase: 'https://centralpiedmont.github.io/degree-explorer/tech/sheets',
  infoSessionUrl: 'https://forms.office.com/pages/responsepage.aspx?id=kftMRq3oAUCotWOPZymUNXQqV-xPK0xLl_usffYhEe1UNkNEWERTT1ZTOVlHVlJDUkg2REdaR1UyTC4u&route=shorturl',
  theme: { /* track colors are supplied by world entries + styles.css vars; reserved for future overrides */ },
  features: { worldTilePhotos: false, admissions: false, specializations: false },
  copy: {
    topbarLabel: 'Information Technology',
    attractSub: 'Explore 14 IT degrees and find yours in three taps.',
    infoButton: 'Sign up for an information session',
    ceHeading: 'IT Certifications &amp; Short Courses',
    resultEyebrow: 'YOUR IT HERO',
  },
  tileTint: {
    'cybersecurity-blueteam': { color: '#005D83', text: '#FFFFFF' },
    'cybersecurity-redteam': { color: '#A4262C', text: '#FFFFFF' },
  },
  tileDesc: {
    'softwareeng-app-dev': 'Build desktop and mobile applications',
    'softwareeng-full-stack': 'Build web apps, front end to back end',
    'artificial-intelligence': 'Train machine-learning models and AI',
    'dataanalysis-analysis': 'Find insights in data with stats and tools',
    'dataanalysis-visualization': 'Turn data into clear charts and dashboards',
    'dataanalysis-google': 'Manage IT projects and analyze data',
    'cybersecurity-blueteam': 'Defend networks and respond to attacks',
    'cybersecurity-redteam': 'Ethical hacking and penetration testing',
    'cybersecurity-forensics': 'Investigate breaches and recover evidence',
    'cloud-networking': 'Build and secure networks and the cloud',
    'it-technical-support': 'Set up, troubleshoot, and support tech',
    'sgd-programming': 'Code the engines and logic behind games',
    'sgd-design': 'Design game worlds, levels, and play',
    'sgd-3d-modeling': 'Model and animate 3D characters and scenes',
  },
  worlds: [
    { id: 'apps',  name: 'Build Apps & Software',
      desc: 'Code websites, mobile apps, and software',
      color: '#005D83', text: '#FFFFFF',
      programIds: ['softwareeng-app-dev', 'softwareeng-full-stack'] },
    { id: 'data',  name: 'Work with Data & AI',
      desc: 'Turn data into insight and build AI',
      color: '#54565A', text: '#FFFFFF',
      programIds: ['artificial-intelligence', 'dataanalysis-analysis', 'dataanalysis-visualization', 'dataanalysis-google'] },
    { id: 'cyber', name: 'Cyber & Networks',
      desc: 'Defend systems and run networks',
      color: '#B4A269', text: '#1A1A1A',
      programIds: ['cybersecurity-blueteam', 'cybersecurity-redteam', 'cybersecurity-forensics', 'cloud-networking'] },
    { id: 'games', name: 'Games & 3D',
      desc: 'Create games, animation, and 3D worlds',
      color: '#672666', text: '#FFFFFF',
      programIds: ['sgd-programming', 'sgd-design', 'sgd-3d-modeling'] },
    { id: 'start', name: 'Not sure — start with IT Support',
      desc: 'New to tech? Start with the essentials',
      color: '#54565A', text: '#FFFFFF',
      programIds: ['it-technical-support'] },
  ],
};
